baseURL = "https://www.nagamocha.dev/"
languageCode = "en-us"
title = "Naga Mocha"
theme = "hugo-ink"
enableEmoji = true
# watch = true
# paginate = 10

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"
pluralizeListTitles =  false


googleAnalytics = "UA-167226613-1"


[params]
	subtitle = "select time 'allballs';"

	avatar = "/coffee.png"

	featherIconsCDN = true

	mode = "dark" # "dark" or "auto"
	customCSS = "css/style.css" # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2

[[menu.main]]
name = "Misc"
url = "/misc"
weight = 3

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/nagamocha3000"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://www.twitter.com/nagamocha"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"